export const SideWrapperData = [
    { id:"advancedTopics",
      url:"#", 
      title:"Advanced Topics",
      children:[{ id:"reactContext", url:"AdvancedTopics/ReactContext", title:"React Context" },
          { id:"redux", url:"AdvancedTopics/Redux", title:"Redux" },
          { id:"rxJs", url:"AdvancedTopics/RxJS", title:"RxJS" }]
    },
    { id:"codeEditorsViewers",
      url:"#", 
      title:"Code Editors / Viewers",
      children:[{ id:"highlight", url:"CodeEditorsViewers/Highlight", title:"Highlight" },
                { id:"stackblitz", url:"CodeEditorsViewers/Stackblitz", title:"Stackblitz" }]
    },
    { id:"components",
      url:"#", 
      title:"Components",
      children:[{ id:"accordian", url:"Component/AccordianList", title:"Accordian" },
            { id:"accordianListItems", url:"Component/AccordianListItems", title:"AccordianListItems" },
            {  id:"alert", url:"Component/Alert", title:"Alert" },
            { id:"avatar", url:"Component/Avatar", title:"Avatar" },
            { id:"badge", url:"Component/Badge", title:"Badge" },
            { id:"breadcrumb", url:"Component/Breadcrumb", title:"Breadcrumb" },
            { id:"button", url:"Component/Button", title:"Button" },
            { id:"calendar", url:"Component/Calendar", title:"Calendar" },
            { id:"card", url:"Component/Card", title:"Card" },
            { id:"carousel", url:"Component/Carousel", title:"Carousel" },
            { id:"drawer", url:"Component/Drawer", title:"Drawer" },
            { id:"hover", url:"Component/Hover", title:"Hover" },
            { id:"loading", url:"Component/Loading", title:"Loading" },
            { id:"menu", url:"Component/Menu", title:"Menu" },
            { id:"modal", url:"Component/Modal", title:"Modal" },
            { id:"progressBar", url:"Component/ProgressBar", title:"ProgressBar" },
            { id:"table", url:"Component/Table", title:"Table" },
            { id:"tag", url:"Component/Tag", title:"Tag" },
            { id:"toast", url:"Component/Toast", title:"Toast" },
            ]
           },
    { id:"features",
      url:"#", 
      title:"Features",
      children:[{ id:"appRouting", url:"Feature/AppRouting", title:"App Routing" },
               { id:"speechListener", url:"Feature/SpeechListener", title:"Speech Listener" }]
    },
    { id:"formElements",
      url:"#", 
      title:"Form Elements",
      children:[{ id:"autocomplete", url:"FormElement/Autocomplete", title:"Autocomplete" },
              { id:"choice", url:"FormElement/Choice", title:"Choice" },
              { id:"colorPicker", url:"FormElement/ColorPicker", title:"ColorPicker" },
              { id:"dateTimePicker", url:"FormElement/DateTimePicker", title:"DateTimePicker" },
              { id:"dropdown", url:"FormElement/Dropdown", title:"Dropdown" },
              { id:"Email", url:"FormElement/Email", title:"Email" },
              { id:"FileUpload", url:"FormElement/FileUpload", title:"FileUpload" },
              { id:"Password", url:"FormElement/Password", title:"Password" },
              { id:"range", url:"FormElement/Range", title:"Range" },
              { id:"selectDropdown", url:"FormElement/SelectDropdown", title:"Select" },
              { id:"switch", url:"FormElement/Switch", title:"Switch" },
              { id:"textArea", url:"FormElement/TextArea", title:"TextArea" },
              { id:"textBox", url:"FormElement/TextBox", title:"TextBox" }]
              
    },
    { id:"headersAndFooters",
      url:"#", 
      title:"Headers and Footers",
      children:[{ id:"headings", url:"HeadersAndFooters/Headings", title:"Headings" }]
    },
    { id:"layouts",
      url:"#", 
      title:"Layouts",
      children:[{ id:"fonts", url:"Layout/Fonts", title:"Fonts" },
      { id:"gridSystem", url:"Layout/GridSystem", title:"GridSystem" },
      { id:"order", url:"Layout/Order", title:"Order" }]
    },
    { id:"readyMadeScreen",
      url:"#", 
      title:"Ready-Made Screens",
      children:[{ id:"authentication", url:"ReadyMadeScreen/Authentication", title:"Authentication" },
      { id:"imageGallery", url:"ReadyMadeScreen/ImageGallery", title:"ImageGallery" },
      { id:"readyMadeDropdowns", url:"ReadyMadeScreen/ReadyMadeDropdowns", title:"Ready-Made Dropdowns" }]
    },
    { id:"themes",
      url:"#", 
      title:"Themes",
      children:[{ id:"appColors", url:"Themes/AppThemes", title:"AppThemes" }]
    },
    { id:"Visualization",
      url:"#", 
      title:"Visualization",
      children:[{ id:"areaChart", url:"Visualization/AreaChart", title:"AreaChart" },
               { id:"barChart", url:"Visualization/BarChart", title:"BarChart" },
               { id:"boxChart", url:"Visualization/BoxChart", title:"BoxChart" },
               { id:"compositionChart", url:"Visualization/CompositionChart", title:"CompositionChart" },
               { id:"correlationChart", url:"Visualization/CorrelationChart", title:"CorrelationChart" },
               { id:"dendogramChart", url:"Visualization/DendogramChart", title:"DendogramChart" },
               { id:"flowChart", url:"Visualization/FlowChart", title:"FlowChart" },
               { id:"funnelChart", url:"Visualization/FunnelChart", title:"FunnelChart" },
               { id:"lineChart", url:"Visualization/LineChart", title:"LineChart" },
               { id:"pieChart", url:"Visualization/PieChart", title:"PieChart" },
               { id:"sankeyChart", url:"Visualization/SankeyChart", title:"SankeyChart" },
               { id:"scatterChart", url:"Visualization/ScatterChart", title:"ScatterChart" },
               { id:"treeMapChart", url:"Visualization/TreeMapChart", title:"TreeMapChart" },
               { id:"twoByTwoChart", url:"Visualization/TwoByTwoChart", title:"TwoByTwoChart" },
               { id:"vennChart", url:"Visualization/VennChart", title:"VennChart" },
               { id:"waterfallChart", url:"Visualization/WaterfallChart", title:"WaterfallChart" }]
    }
];