export const SideWrapperData = [
    { id:"components",
      url:"#", 
      title:"Components",
      children:[{ id:"accordian", url:"Component/AccordianList", title:"Accordian" },
            { id:"accordianListItems", url:"Component/AccordianListItems", title:"AccordianListItems" },
            {  id:"alert", url:"Component/Alert", title:"Alert" },
            { id:"avatar", url:"Component/Avatar", title:"Avatar" },
            { id:"badge", url:"Component/Badge", title:"Badge" },
            { id:"breadcrumb", url:"Component/Breadcrumb", title:"Breadcrumb" },
            { id:"button", url:"Component/Button", title:"Button" },
            { id:"calendar", url:"Component/Calendar", title:"Calendar" },
            { id:"card", url:"Component/Card", title:"Card" },
            { id:"carousel", url:"Component/Carousel", title:"Carousel" },
            { id:"dropdown", url:"Component/Dropdown", title:"Dropdown" },
            { id:"drawer", url:"Component/Drawer", title:"Drawer" },
            { id:"listGroup", url:"Component/ListGroup", title:"ListGroup" },
            { id:"modal", url:"Component/Modal", title:"Modal" },
            { id:"ruleBuilder", url:"Component/RuleBuilder", title:"RuleBuilder" },
            { id:"table", url:"Component/Table", title:"Table" },
            { id:"tabs", url:"Component/Tabs", title:"Tabs" },
            { id:"tag", url:"Component/Tag", title:"Tag" },
            { id:"toast", url:"Component/Toast", title:"Toast" },
            { id:"toolTip", url:"Component/ToolTip", title:"ToolTip" },
            { id:"loading", url:"Component/Loading", title:"Loading" }]
           },
    { id:"features",
      url:"#", 
      title:"Features",
      children:[{ id:"appRouting", url:"Feature/AppRouting", title:"App Routing" },
               { id:"speechListener", url:"Feature/SpeechListener", title:"Speech Listener" }]
    },
    { id:"formElements",
      url:"#", 
      title:"Form Elements",
      children:[{ id:"autocomplete", url:"FormElement/Autocomplete", title:"Autocomplete" },
              { id:"selectDropdown", url:"FormElement/SelectDropdown", title:"Select" },
              { id:"textBox", url:"FormElement/TextBox", title:"TextBox" },
              { id:"textArea", url:"FormElement/TextArea", title:"TextArea" },
              { id:"colorPicker", url:"FormElement/ColorPicker", title:"Color Picker" },
              { id:"choice", url:"FormElement/Choice", title:"Choice" },
              { id:"dateTimeRangePicker", url:"FormElement/DateTimeRangePicker", title:"DateTimeRangePicker" },
              { id:"dateTimePicker", url:"FormElement/DateTimePicker", title:"DateTimePicker" },
              { id:"range", url:"FormElement/Range", title:"Range" },
              { id:"inputGroup", url:"FormElement/InputGroup", title:"InputGroup" }]
    },
    { id:"headersAndFooters",
      url:"#", 
      title:"Headers and Footers",
      children:[{ id:"headings", url:"HeadersAndFooters/Headings", title:"Headings" }]
    },
    { id:"layouts",
      url:"#", 
      title:"Layouts",
      children:[{ id:"fonts", url:"Layout/Fonts", title:"Fonts" },
      { id:"grid", url:"Layout/Grid", title:"Grid" },
      { id:"order", url:"Layout/Order", title:"Order" }]
    },
    { id:"Visualization",
      url:"#", 
      title:"Visualization",
      children:[{ id:"areaChart", url:"Visualization/AreaChart", title:"AreaChart" },
               { id:"barChart", url:"Visualization/BarChart", title:"BarChart" },
               { id:"boxChart", url:"Visualization/BoxChart", title:"BoxChart" },
               { id:"compositionChart", url:"Visualization/CompositionChart", title:"CompositionChart" },
               { id:"correlationChart", url:"Visualization/CorrelationChart", title:"CorrelationChart" },
               { id:"dendogramChart", url:"Visualization/DendogramChart", title:"DendogramChart" },
               { id:"flowChart", url:"Visualization/FlowChart", title:"FlowChart" },
               { id:"funnelChart", url:"Visualization/FunnelChart", title:"FunnelChart" },
               { id:"lineChart", url:"Visualization/LineChart", title:"LineChart" },
               { id:"pieChart", url:"Visualization/PieChart", title:"PieChart" },
               { id:"sankeyChart", url:"Visualization/SankeyChart", title:"SankeyChart" },
               { id:"scatterChart", url:"Visualization/ScatterChart", title:"ScatterChart" },
               { id:"treeMapChart", url:"Visualization/TreeMapChart", title:"TreeMapChart" },
               { id:"twoByTwoChart", url:"Visualization/TwoByTwoChart", title:"TwoByTwoChart" },
               { id:"vennChart", url:"Visualization/VennChart", title:"VennChart" },
               { id:"waterfallChart", url:"Visualization/WaterfallChart", title:"WaterfallChart" }]
    },
    { id:"themes",
      url:"#", 
      title:"Themes",
      children:[{ id:"appColors", url:"Themes/AppColors", title:"App Colors" }]
    },
    { id:"codeEditorsViewers",
      url:"#", 
      title:"Code Editors / Viewers",
      children:[{ id:"highlight", url:"CodeEditorsViewers/Highlight", title:"Highlight" },
                { id:"stackblitz", url:"CodeEditorsViewers/Stackblitz", title:"Stackblitz" }]
    },
    { id:"advancedTopics",
      url:"#", 
      title:"Advanced Topics",
      children:[{ id:"redux", url:"AdvancedTopics/Redux", title:"Redux" },
      { id:"rxJs", url:"AdvancedTopics/RxJS", title:"RxJS" }]
    },
    { id:"readyMadeScreen",
      url:"#", 
      title:"Ready-Made Screens",
      children:[{ id:"authentication", url:"ReadyMadeScreen/Authentication", title:"Authentication" },
      { id:"imageGallery", url:"ReadyMadeScreen/ImageGallery", title:"ImageGallery" },
      { id:"readyMadeDropdowns", url:"ReadyMadeScreen/ReadyMadeDropdowns", title:"Ready-Made Dropdowns" }]
    }
];